# Generated by Django 5.0.9 on 2024-10-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("seller", "Seller"), ("shopper", "Shopper")],
                default="shopper",
            ),
        ),
    ]
