# Generated by Django 5.0.9 on 2024-10-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0002_product_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="commerce.category"),
        ),
    ]
