# Generated by Django 5.0.9 on 2024-10-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0004_order_delivery_address_order_delivery_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
