# Generated by Django 5.0.9 on 2024-10-19 01:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_product_image_alter_auction_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.TextField(default=datetime.datetime(2024, 10, 19, 1, 25, 46, 976323, tzinfo=datetime.timezone.utc), editable=False, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_id', 'product'), name='unique_order_product'),
        ),
    ]
