# Generated by Django 5.0.9 on 2024-10-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_remove_order_unique_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_order_product',
        ),
    ]
